server:
  port: 8761
spring:
  applcation:
    name: eureka-server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: http://localhost:8761

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN